[package]
name = "cli-ws-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
serde = { version = "1.0.209", features = [ "serde_derive" ] }
serde_json = "1.0.127"
sha3 = "0.10.8"
tungstenite = "0.24.0"

